:sparkles: adiciona N-step Q-learning
GrupoTuring/Aprendizado-por-Reforco pull request #22
Opened 2020-09-10 20:03 UTC by luish18

Primeira iteração do notebook de N-step feito por mim e pelo @Berbardo.

Closes #21

2020-09-11 00:25 UTC, Berbardo submitted a review, later dismissed

2020-09-11 00:25 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/N-step Q-learning/README.md
> + # N-step DQN
Acho que dá pra botar tudo até Off-policy N-step aqui. Também falta linkar o notebook aqui

2020-09-11 00:25 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/README.md
> +## [N-step Q-learning](N-step%20Q-learning)
Coloca o nome da pasta de N-Step DQN acho, sepá ficaria melhor

2020-09-12 00:32 UTC, Berbardo commented
Falta talvez colocar o pseudo-código do algoritmo?

2020-10-02 20:27 UTC, nelsonayamashita approved these changes
Pra mim pareceu tudo certo, pode dar merge.

2020-10-02 20:38 UTC, Berbardo commented
Acabei de perceber que não colocamos o pseudocódigo do algoritmo, vocês acham que faz sentido apesar de mudar pouca coisa da DQN normal?

2020-10-02 20:55 UTC, nelsonayamashita commented
Hmm, mesmo que seja pouca coisa acho que ajuda a entender melhor... 
Justamente por ser pouca a diferença acho que o pseudocódigo pode ajudar a enfatizar o que está diferente, acho que vale a pena fazer.

2020-10-02 21:02 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/N-step DQN/README.md
> +Para fazermos uma implementação tecnicamente ¨completa¨ de n-step *off-policy*, seria necessário implementar a funcionalidade de *importance sampling* no n-step buffer. Isso necessariamente requer qu
Talvez seja bom explicar porque precisa de importance sampling.

2020-10-02 21:07 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/N-step DQN/N-Step DQN.ipynb
> +    "        done: int\n",
Não sei o que eu acho de falar que `done` é `int`. Por um lado tá certo, porque `bool` é uma subclasse de `int`. Por outro lado, vocês nunca usam como `int`. Na hora de chamar o `NStepBuffer`, vocês sempre passam `bool`, e o array `NStepBuffer.dones` é um array de `float32`.

Enfim, se quiserem deixar assim não tem problema.

2020-10-02 21:15 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/N-step DQN/N-Step DQN.ipynb
> +    "        if any(G for G in episode_returns):\n",
Algum motivo específico pra ignorar retorno zero?
Pra mim faria mais sentido só verificar se `episode_returns` é vazio ou não:
```python
if episode_returns:
    ...
```

2020-10-02 21:18 UTC, fernandokm requested changes

2020-10-02 21:18 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/N-step DQN/README.md
> +Para fazermos uma implementação tecnicamente ¨completa¨ de n-step *off-policy*, seria necessário implementar a funcionalidade de *importance sampling* no n-step buffer. Isso necessariamente requer qu
Talvez seja bom explicar porque precisa de importance sampling.

2020-10-02 21:18 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/N-step DQN/N-Step DQN.ipynb
> +    "        if any(G for G in episode_returns):\n",
Algum motivo específico pra ignorar retorno zero?
Pra mim faria mais sentido só verificar se episode_returns é vazio ou não:
```python
if episode_returns:
    ...
```

2020-10-02 21:18 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/N-step DQN/N-Step DQN.ipynb
> +    "        done: int\n",
Não sei o que eu acho de falar que `done` é `int`. Por um lado tá certo, porque `bool` é uma subclasse de `int`. Por outro lado, vocês nunca usam como `int`. Na hora de chamar o `NStepBuffer`, vocês sempre passam `bool`, e o array `NStepBuffer.dones` é um array de `float32`.

Enfim, se quiserem deixar assim não tem problema.

2020-10-18 16:13 UTC, nelsonayamashita approved these changes
Talvez só precise colocar o pseudo algoritmo... Mas de resto eu acho que tá tudo certo e pode dar merge.

2020-10-22 22:30 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/N-step DQN/README.md
> +Para fazermos uma implementação tecnicamente ¨completa¨ de n-step *off-policy*, seria necessário implementar a funcionalidade de *importance sampling* no n-step buffer. Isso necessariamente requer qu
Update depois de f4f34c9911163a799ee42aed42cceba2e19d9db2.

Acho que não ficou perfeito, mas também acho difícil deixar isso muito bem explicado sem complicar o texto. Do jeito que tá, me parece um bom trade-off

2020-10-22 22:31 UTC, fernandokm approved these changes

2020-10-23 02:07 UTC, merged