Deep q learning
GrupoTuring/Aprendizado-por-Reforco pull request #23
Opened 2020-09-27 18:42 UTC by dueiras

Falta consertar o README e adicionar uma visualização do resultado, mas já deixo aqui o **PR** para melhorar eventuais defeitos ou falta de coisas.

2020-10-05 16:06 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Deep Q-Network/README.md
> +Aconselhemos a leitura da nossa implementação de Q-Learning caso você não esteja tão acostumado com o algoritmo original e os conceitos básicos, pois isso facilitará seu entendimento de uma ```DQN```
Talvez DQN ou **DQN** ao invés de `DQN`? Geralmente `esse formato` é usado pra código.

2020-10-05 17:04 UTC, fernandokm submitted a review, later dismissed
- Mudar o nome da pasta "Imagens" para "imgs", conforme [essas instruções](https://github.com/GrupoTuring/Aprendizado-por-Reforco/blob/master/Ferramentas/README.md#algoritmos).

PS: ainda to tentando entender o que o commit de experience replay do @Berbardo tá fazendo aqui

2020-10-05 17:04 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Deep Q-Network/DQN.ipynb
> +    "train(dqn_net, env, timesteps, render=False)"
Acho que seria legal colocar alguma indicação de performance do agente. Do jeito que tá agora, não dá pra saber se funcionou mesmo (dá pra baixar o notebook e rodar um episódio com renderização, mas o notebook em si não mostra nada).

Por exemplo, daria pra colocar um gráfico de retorno, e.g., o que foi feito [aqui](https://github.com/GrupoTuring/Aprendizado-por-Reforco/blob/master/Aprendizado%20por%20Refor%C3%A7o%20Cl%C3%A1ssico/Monte%20Carlo/Monte%20Carlo%20Every-Visit/Monte%20Carlo%20Every-Visit.ipynb).

2020-10-26 11:32 UTC, Berbardo requested changes
Acho que agora só falta os algoritmos em LaTeX da DQN e da N-Step DQN

2020-10-31 17:15 UTC, nelsonayamashita reviewed
Acho que tá tudo certo no código e nos .md's.
Coloquei os pseudo códigos, depois deem uma olhada.

2020-10-31 17:15 UTC, Berbardo requested changes
Só faltou colocar o pseudocódigo no README de N-Step

2020-10-31 17:31 UTC, Berbardo approved these changes

2020-11-01 21:38 UTC, fernandokm requested changes

2020-11-01 21:38 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Deep Q-Network/README.md
> +<img src="https://latex.codecogs.com/svg.latex?Q(S_t,&space;A_t)&space;\leftarrow&space;Q(S_t,&space;A_t)&space;&plus;&space;\alpha&space;[R_{t&plus;1}&space;&plus;&space;\gamma&space;max_a&space;Q(S
Corrige a renderização do `max`.
```suggestion
- Target: <img src="https://latex.codecogs.com/svg.latex?\max_a&space;Q(S_{t&plus;1},&space;a)" title="\max_a Q(S_{t+1}, a)" />

E nossa função fica, assim como já visto em Q-Learning:

<img src="https://latex.codecogs.com/svg.latex?Q(S_t,&space;A_t)&space;\leftarrow&space;Q(S_t,&space;A_t)&space;&plus;&space;\alpha&space;[R_{t&plus;1}&space;&plus;&space;\gamma&space;\max_a&space;Q(S_{t&plus;1},&space;a)&space;-&space;Q(S_t,&space;A_t)]" title="Q(S_t, A_t) \leftarrow Q(S_t, A_t) + \alpha [R_{t+1} + \gamma \max_a Q(S_{t+1}, a) - Q(S_t, A_t)]" />
```

2020-11-01 21:38 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Deep Q-Network/README.md
> +Esse tipo de aprendizado é chamado de **off-policy**, porque ele não acontece ao mesmo tempo em que nosso agente explora o ambiente.
Off-policy é mais pela questão das políticas usadas pra obter as observações serem diferentes da política atual. Algo como isso (podem melhorar se tiverem ideias):

```suggestion
Nesse tipo de aprendizagem, os dados que o agente recebe podem vir de qualquer instante de tempo passado, ou seja, esses dados foram obtidos com políticas variadas (visto que a política do agente varia no tempo). Por outro lado, a política que está sendo aprendida pelo agente é a política ótima  &pi;* (e a função ótima _q_*). Esse tipo de aprendizado é chamado de **off-policy**, porque a política que está sendo aprendida é diferente da política de exploração, utilizada para obter os dados.
```

2020-11-01 21:38 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Experience Replay/README.md
> +Uma grande desvantagem das redes neurais é a necessidade de treinar com uma grande quantidade de dados para obter um bom aprendizado. Isso torna seu uso em algoritmos "online" como os de Temporal Dif
Era pra ser on-policy ao invés de online? E mesmo nesse caso acho que teria que ser sarsa, não TD.

2020-11-01 22:32 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Experience Replay/README.md
> +Uma grande desvantagem das redes neurais é a necessidade de treinar com uma grande quantidade de dados para obter um bom aprendizado. Isso torna seu uso em algoritmos "online" como os de Temporal Dif
Acho que é online mesmo, todos os algoritmos de TD clássicos são online porque eles dão update a cada nova experiência que eles recebem.

2020-11-01 22:53 UTC, fernandokm approved these changes

2020-11-01 22:58 UTC, Berbardo approved these changes

2020-11-01 22:58 UTC, fernandokm approved these changes

2020-11-02 12:24 UTC, merged