:sparkles: Adiciona arquivos iniciais da DDQN
GrupoTuring/Aprendizado-por-Reforco pull request #31
Opened 2020-11-15 18:07 UTC by nelsonayamashita

Coloquei os primeiros arquivos da DDQN: notebook com o código e os resultados do treinamento, ainda é preciso colocar toda a teoria e o texto do README.

2021-01-18 21:55 UTC, Berbardo requested changes
Só revisei o README. Tá certinho, talvez só acrescentar mais coisas.

Acho interessante ou comentar mais de viés de maximização ou deixar algum link pra algo explicando o conceito também.

2021-01-18 21:55 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +
Talvez colocar uma descrição genérica do que é DDQN tipo:

"Uma extensão do algoritmo de DQN com correção de viés que estabiliza a performance do treinamento do agente"

ou alguma enrolação assim.

2021-01-18 21:55 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +Esse algoritmo, como sabemos, tem como objetivo atualizar as estimativas dos Q valores para os pares estado-ação do ambiente. O valor de Q é atualizado por meio de uma "parcela de correção de erro" (
```suggestion
Esse algoritmo, como sabemos, tem como objetivo atualizar as estimativas dos Q valores para os pares estado-ação do ambiente. O valor de Q é atualizado por meio de uma "parcela de correção de erro" (parcela de atualização), com uma taxa de aprendizado α.
```

2021-01-18 21:55 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +o Q target vira a soma da recompensa ao tomar a ação a no estado s, mais o valor máximo de q dentre todas as possíveis ações no estado seguinte descontado do Q anterior.
```suggestion
O Q target vira a soma da recompensa ao tomar a ação a no estado s, mais o valor máximo de **Q** dentre todas as possíveis ações no estado seguinte descontado do Q anterior.
```

Não entendi o descontado do Q anterior também.

2021-01-18 21:55 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +Mas o problema enfrentado é que não temos o **q(s,a)**
```suggestion
Mas o problema enfrentado é que não temos o **q(s,a)**.
```

2021-01-18 21:55 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +  - Usamos uma rede DQN para selecionar qual é a melhor ação a ser tomada no próximo estado (ação com maior q-valor)
```suggestion
  - Usamos uma rede DQN para selecionar qual é a melhor ação a ser tomada no próximo estado. (Ação com maior q-valor.)
```

2021-01-18 21:55 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +  - Rede DQN para escolher melhor ação para o próximo estado:  <img src="https://latex.codecogs.com/svg.latex?Q(s',&space;argmax_a&space;Q(s',a))" title="Q(s', argmax_a Q(s',a))" />
A notação dá a entender que os dois Qs são iguais, que vem da mesma rede neural / dos mesmos pesos.

2021-01-19 11:32 UTC, Berbardo requested changes
Tem que fazer as mudanças do README no notebook tb

2021-01-19 11:32 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +O Q target vira a soma da recompensa ao tomar a ação a no estado s, mais o valor máximo de **Q** dentre todas as possíveis ações no estado seguinte descontado do Q anterior.
Ainda não entendi mt bem o descontado do Q anterior.

2021-01-19 11:32 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +    <img src="https://latex.codecogs.com/svg.latex?Q(s',&space;argmax_a&space;Q(s',a))" title="Q(s', argmax_a Q(s',a))" />
Ainda não tem nada na notação diferenciando o Q da rede principal e o Q de target, talvez colocar pesos diferentes pra eles subscritos ou colocar um Q' pro target.

2021-01-19 19:53 UTC, nelsonayamashita commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +    <img src="https://latex.codecogs.com/svg.latex?Q(s',&space;argmax_a&space;Q(s',a))" title="Q(s', argmax_a Q(s',a))" />
Eu deixei os nomes como $Q_{local}$ e $Q_{alvejado}$, respectivamente, acha que são bons nomes? Depois dá uma olhada como ficou o texto e me diz o que acha

2021-01-19 19:56 UTC, nelsonayamashita commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +O Q target vira a soma da recompensa ao tomar a ação a no estado s, mais o valor máximo de **Q** dentre todas as possíveis ações no estado seguinte descontado do Q anterior.
Deixei melhor explicado do que eu entendi da frase original. Eu tinha pego da aula e não tinha achado tão claro tbm. Depois me diz o que achou da frase nova.

2021-01-20 02:06 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +O Q target vira a soma da recompensa ao tomar a ação a no estado s, mais o valor máximo de **Q** dentre todas as possíveis ações no estado seguinte descontado do Q anterior.
ahhh entendi agora, ficou mais claro

2021-02-26 20:11 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "class DDQNAgent:\n",
Acho que poderia colocar mais comentários, caso contrário, o usuário precisaria estar com os dois códigos para entender melhor a estrutura do código,

2021-02-26 20:12 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "def train(agent, env, timesteps, render=False):\n",
Adicionar mais comentários, para facilitar o entendimento do código.

2021-02-26 20:14 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "plt.plot(train_returns, 'r')\n",
Poderia ser interessante adicionar um agente DQN para comparar o comportamento, visto que os dois modelos são comparados a todo momento do texto.

2021-02-26 20:15 UTC, FelipeAugustoMachado approved these changes

2021-02-26 20:15 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Deep Q-Learning/README.md
> +Uma extensão do algoritmo de DQN com correção de viés que estabiliza a performance do treinamento do agente
Adicionar ponto final.

2021-02-26 20:25 UTC, rafael-acoelho commented
Trê coisinhas pra arrumar no texto introdutório:
- Arrumar o "o" duplicado no segundo parágrafo.

- No primeiro parágrafo da teoria, trocar "surgiram como o objetivo" por "surgiram com o objetivo".

- Em "Solução" no segundo item "... estado. (Ação com maior q-valor.)", tirar o primeiro ponto final e colocar o segundo para fora do parênteses.

2021-02-26 20:26 UTC, Berbardo requested changes
Coloquei alguns comentários aí. Alguns são correções e outros são só perguntas do que vocês preferem.

2021-02-26 20:26 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Q(s,a) \\leftarrow Q(s,a) + \\alpha [R(s,a) + \\gamma \\cdot  max_{a'} Q'(s', a') - Q(s,a)]\n",
```suggestion
    "Q(s,a) \\leftarrow Q(s,a) + \\alpha [R(s,a) + \\gamma \\cdot  \max_{a'} Q'(s', a') - Q(s,a)]\n",
```

Aqui dá pra colocar o ```max``` como um ```\max``` ou um ```\mathrm{max}```

2021-02-26 20:26 UTC, Berbardo commented on .gitignore
> +.vscode/settings.json
```suggestion
.vscode/
```

aqui talvez colocar só .vscode?

2021-02-26 20:26 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Q(s,a) \\leftarrow Q(s,a) + \\alpha [R(s,a) + \\gamma \\cdot  max_{a'} Q'(s', a') - Q(s,a)]\n",
No notebook de DQN a gnt usou ```R_{t+1}``` em vez ```R(s, a)```, qual vocês preferem?

2021-02-26 20:26 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "A atualização é composta pela recompensa imediata pela última ação tomada **R(s,a)**, o fator de desconto γ multiplicando o o maior valor possível esperado de retorno naquele novo estado (após a
```suggestion
    "A atualização é composta pela recompensa imediata pela última ação tomada **R(s,a)**, o fator de desconto γ multiplicando o maior valor possível esperado de retorno naquele novo estado (após a última ação) menos o valor atual de Q.\n",
```

Essa parte do maior valor possível ficou clara?

2021-02-26 20:26 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Q_{bootstrap}(s,a) = r(s,a) + \\gamma \\cdot \\operatorname{max}_{a}Q(s',a)\n",
Aqui estamos usando ```r(s,a)``` quando lá em cima usamos ```R(s, a)```, não sei qual o certo.

2021-02-26 20:26 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "O Q target vira a soma da recompensa ao tomar a ação a no estado s, mais o valor máximo de **Q** dentre todas as possíveis ações. Repare que, basicamente o que estamos fazendo é criar uma estima
```suggestion
    "O Q target vira a soma da recompensa ao tomar a ação $a$ no estado $s$, mais o valor máximo de **Q** dentre todas as possíveis ações. Repare que, basicamente o que estamos fazendo é criar uma estimativa nova que depende dela mesma; que depende de uma estimativa anterior que está constantemente mudando:\n",
```

2021-02-26 20:26 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Mas o que pode acontecer a partir disso é que estaremos escolhendo ações que possuem o maior q-valor sem ter tanta certeza de que isso não é um falso positivo, de que não estamos obtendo um q-va
Dá pra mencionar que o nome do viés é ***Maximization Bias***, e colocar algum link que explique a fundo tipo o livro ou algo assim.

2021-02-26 20:26 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "  -  Usamos uma rede DQN $Q_{alvejado}$ para calcular o q-valor de tomar essa ação no próximo estado.\n",
Preferem _alvejado_ ou _target_?

2021-02-26 20:31 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "  -  Usamos uma rede DQN $Q_{alvejado}$ para calcular o q-valor de tomar essa ação no próximo estado.\n",
Eu prefixo target

2021-02-26 20:32 UTC, rafael-acoelho commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +A atualização é composta pela recompensa imediata pela última ação tomada **R(s,a)**, o fator de desconto γ multiplicando o o maior valor possível esperado de retorno naquele novo estado (após a últi
Arrumar o "o" duplicado.

2021-02-26 20:32 UTC, rafael-acoelho commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +Talvez você tenha notado que no algoritmo de Q-learning nós utilizamos uma estimativa do q-valor para fazer uma estimativa do nosso q-valor, as DDQN's surgiram como o objetivo de lidar com este probl
Trocar "surgiram como o objetivo" por "surgiram com o objetivo".

2021-02-26 20:32 UTC, rafael-acoelho commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +  - Usamos uma rede DQN **Q**<sub>*local*</sub> para selecionar qual é a melhor ação a ser tomada no próximo estado. (Ação com maior q-valor.)
Em "... estado. (Ação com maior q-valor.)", tirar o primeiro ponto final e colocar o segundo para fora do parênteses.

2021-02-26 20:32 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Q(s,a) \\leftarrow Q(s,a) + \\alpha [R(s,a) + \\gamma \\cdot  max_{a'} Q'(s', a') - Q(s,a)]\n",
Eu colocaria `R_{t+1}` ou `r`. Usar `R(s,a)` tá errado, porque não é a recompensa média pro par `(s,a)`, mas a recompensa real (empírica) no instante `t+1`.

2021-02-26 20:40 UTC, Berbardo requested changes

2021-02-26 20:40 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "  - Rede $Q_{fixo}$ calculando $Q$ valor da escolha acima:\n",
Aqui esse Q é Q_fixo mesmo?

2021-02-26 20:40 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "$Q_{local}(s,a) = r(s,a) + \\gamma \\cdot Q_{alvejado}(s', \\operatorname{argmax_a} Q_{local}(s',a))$\n",
Aqui tem o r(s, a) minúsculo diferente tb

2021-02-26 20:40 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Importante notar que faremos apenas o proceso de *backpropagation* na rede local. Para a rede alvejada nós copiaremos os parâmetros de uma para a outra, com um parâmetro $\\tau$ definindo quanto
Aqui deu pra entender +- como funciona o update da rede de target? @rafael-acoelho @FelipeAugustoMachado

2021-02-26 20:40 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +   ]
Acho importante colocar mais comentários aqui especialmente no treinamento, como o Machado comentou

2021-02-26 21:55 UTC, fernandokm requested changes
Além dos comentários abaixo, tem algumas coisas que eu posso arrumar depois:
- [ ] colocar alguns `\mathrm` no notebook e md
- [ ] atualizar a imagem com o algoritmo

2021-02-26 21:55 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "A atualização é composta pela recompensa imediata pela última ação tomada $R_{t+1}$, o fator de desconto $γ$ multiplicando o maior valor possível esperado de retorno naquele novo estado (após a
O `$γ$` não funciona. Precisa ser `γ` ou `$\gamma$` (o mathjax/latex padrão não suporta unicode).

2021-02-26 21:55 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Talvez você tenha notado que no algoritmo de Q-learning nós utilizamos uma estimativa do q-valor para fazer uma estimativa do nosso q-valor, as DDQN's surgiram como o objetivo de lidar com este
```suggestion
    "Talvez você tenha notado que no algoritmo de Q-learning nós utilizamos uma estimativa do q-valor para fazer uma estimativa do nosso q-valor, as DDQN's surgiram com o objetivo de lidar com este problema.\n",
```
Mesmo problema de https://github.com/GrupoTuring/Aprendizado-por-Reforco/pull/31#discussion_r583900564 mas no notebook.

2021-02-26 21:55 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "  - Usamos uma rede DQN $Q_{local}$ para selecionar qual é a melhor ação a ser tomada no próximo estado. (Ação com maior q-valor).\n",
```suggestion
    "  - Usamos uma rede DQN $Q_{local}$ para selecionar qual é a melhor ação a ser tomada no próximo estado (ação com maior q-valor).\n",
```
Faltou corrigir uma parte do https://github.com/GrupoTuring/Aprendizado-por-Reforco/pull/31#discussion_r583900587

2021-02-26 21:55 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/README.md
> +  - Usamos uma rede DQN **Q**<sub>*local*</sub> para selecionar qual é a melhor ação a ser tomada no próximo estado. (Ação com maior q-valor).
```suggestion
  - Usamos uma rede DQN **Q**<sub>*local*</sub> para selecionar qual é a melhor ação a ser tomada no próximo estado (ação com maior q-valor).
```
Faltou corrigir uma parte do https://github.com/GrupoTuring/Aprendizado-por-Reforco/pull/31#discussion_r583900587

2021-02-26 21:56 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "  - Rede $Q_{fixo}$ calculando $Q$ valor da escolha acima:\n",
Foi arrumado no markdown, mas ainda tá errado no notebook.

2021-03-11 21:37 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Mas o que pode acontecer a partir disso é que estaremos escolhendo ações que possuem o maior q-valor sem ter tanta certeza de que isso não é um falso positivo, de que não estamos obtendo um q-va
Up

2021-04-22 21:54 UTC, nelsonayamashita commented on Aprendizado por Reforço Profundo/Deep Q-Learning/Double DQN/DDQN.ipynb
> +    "Mas o que pode acontecer a partir disso é que estaremos escolhendo ações que possuem o maior q-valor sem ter tanta certeza de que isso não é um falso positivo, de que não estamos obtendo um q-va
Depois de  dois meses coloquei 👍

2021-04-22 22:09 UTC, fernandokm submitted a review, later dismissed

2021-04-22 22:11 UTC, fernandokm approved these changes

2021-04-22 22:13 UTC, Berbardo approved these changes

2021-04-22 22:17 UTC, merged